version: '3'

services:
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: unless-stopped
    networks:
      - oauth-api
    volumes:
      - ${PWD}/out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 20s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      - cassandra
    networks:
      - oauth-api
    volumes:
      - ${PWD}/scripts/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo [ecommerce_oauth]Loading cassandra keyspace... && cqlsh cassandra -f /schema.cql"

  oauth-api-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CASSANDRA_URL=cassandra
    depends_on:
      - cassandra
    networks:
      - oauth-api
    entrypoint: ["/app/wait-for.sh","cassandra:9042", "--", "/app/start.sh"]
    command: ["/app/main"]
   
networks:
  oauth-api:
    driver: bridge
